openapi: 3.0.0
info:
  title: Thicc Peas API
  version: 1.0.0-oas3
  description: ''
servers:
  - url: 'https://thicc-peas-cdc-api-o54gbxra3a-an.a.run.app/'
tags:
  - name: disease
    description: Information pertaining to diseases on the CDC.
  - name: outbreak
    description: Information regarding outbreaks regarding the CDC.
  - name: log
    description: The output logs of the API.
paths:
  /disease:
    get:
      tags:
        - disease
      summary: Get all diseases
      operationId: get-all-disease
      responses:
        '200':
          description: Successfully retrieved list of all diseases
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Diseases'
                
  '/disease/{diseaseName}':
    parameters:
      - schema:
          type: string
        name: diseaseName
        in: path
        required: true
        description: Name of an existing disease.
    get:
      tags:
        - disease
      summary: Get Disease Info by Disease Name
      responses:
        '200':
          description: Disease found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Disease'
        '404':
          description: Disease Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DiseaseNotFound'
      operationId: get-disease-diseaseName
      description: Retrieve the information of the disease with the matching disease name.

  /outbreak:
    get:
      summary: Your GET endpoint
      tags:
        - outbreak
      responses:
        '200':
          description: Successfully retrieved list of all outbreaks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Outbreak'
      operationId: get-report
      description: >
        Retreive all report between the start date provided and the end date
        provide.
      # parameters:
      #   - schema:
      #       type: string
      #     in: query
      #     name: startDate
      #     description: The earliest date to which reports will be queried
      #   - schema:
      #       type: string
      #     in: query
      #     name: endDate
      #     description: The latest date to which reports will be queried
      #   - schema:
      #       type: string
      #     in: query
      #     name: disease
      #     description: The disease to which the report will be based on
          
  '/outbreak/{outbreakID}':
    get:
      tags:
        - outbreak
      summary: Find outbreak by ID
      description: Returns a single outbreak
      operationId: getOutbreakById
      parameters:
        - name: outbreakID
          in: path
          description: ID of outbreak to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successfully return outbreak
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Outbreaks'
        '404':
          description: Outbreak not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DiseaseNotFound'
  
  /log:
    get:
      tags:
        - log
      summary: Find outbreak by ID
      description: Returns all the API's logs
      operationId: getLogs
      responses:
        '200':
          description: Successfully return log files
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Log'


components:
  schemas:
    Log:
      title: Log
      type: object
      properties:
        logs:
          type: array
          items:
            type: string
            example: "2021-03-19T03:59:40.577Z | ::1 requested '/outbreak' - Status Code: 200"
      
  
    OutbreakNotFound:
      title: OutbreakNotFound
      type: object
      properties:
        message:
          type: string
          example: No outbreaks match the ID 90
          
    DiseaseNotFound:
      title: DiseaseNotFound
      type: object
      properties:
        message:
          type: string
          example: No disease match the name COVOD-19
  
    Outbreak:
      title: Outbreak
      type: object
      description: ''
      x-examples:
        Covid-19:
          reportID: 1
          disease_id: 1
          disease_name: covid-19
          locations:
            - 'Lidcombe, NSW, Australia'
          reported_cases: 17
          hospitilisation: 2
          deaths: 0
          startDate: '1997-10-31'
          endDate: '2019-08-24'
          investigationStatus: true
      properties:
        reportID:
          type: integer
          example: 1
          description: Unique identifier for the report.
        disease_name:
          type: string
          example: covid-19
        locations:
          type: array
          items:
            type: string
          example:
            - 'Lidcombe, NSW, Australia'
        reported_cases:
          type: integer
          example: 17
        hospitilisation:
          type: integer
          example: 2
        deaths:
          type: integer
          example: 0
        startDate:
          type: string
          format: date
          example: '1997-10-31'
        endDate:
          type: string
          format: date
          example: '1997-10-31'
        investigationStatus:
          type: boolean
          example: true

    Outbreaks:
      type: array
      items:
        type: object
        properties:
          reportID:
            type: integer
            example: 1
            description: Unique identifier for the report.
          disease_name:
            type: string
            example: covid-19
          locations:
            type: array
            items:
              type: string
            example:
              - 'Lidcombe, NSW, Australia'
          reported_cases:
            type: integer
            example: 17
          hospitilisation:
            type: integer
            example: 2
          deaths:
            type: integer
            example: 0
          startDate:
            type: string
            format: date
            example: '1997-10-31'
          endDate:
            type: string
            format: date
            example: '1997-10-31'
          investigationStatus:
            type: boolean
            example: true
        
    Diseases:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
            description: Unique identifier for the given disease.
            example: 2
          name:
            type: string
            example: Listeria
          symptoms:
            type: array
            items:
              type: object
              properties:
                name:
                  type: string
                  example: Fever
  
    Disease:
      type: object
      properties:
        id:
          type: integer
          description: Unique identifier for the given disease.
          example: 2
        name:
          type: string
          example: Listeria
        symptoms:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
                example: Fever
