version: '3.4'

services:
  apidocumentation:
    image: apidocumentation
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
